### ISSUE TITLE
complete garbage 

### ISSUE THREAD

**Issue by lukascomer** [mekb-turtle/discord-ai-bot#10]
> start
> node src/index.js

[Shard Manager] [INFO] Loading
/root/discord-ai-bot/node_modules/discord.js/src/util/Util.js:69
  if (!token) throw new DiscordjsError(ErrorCodes.TokenMissing);
                    ^

Error [TokenMissing]: Request to use token, but token was unavailable to the client.
    at fetchRecommendedShardCount (/root/discord-ai-bot/node_modules/discord.js/src/util/Util.js:69:21)
    at ShardingManager.spawn (/root/discord-ai-bot/node_modules/discord.js/src/sharding/ShardingManager.js:197:22)
    at file:///root/discord-ai-bot/src/index.js:29:9
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'TokenMissing'
}

Node.js v18.19.0

**Comment by mekb-turtle** [comment]
did you put your discord token in the .env file?

**Comment by lukascomer** [comment]
Yes

**Comment by TheModdersDen** [comment]
> Yes

@mekb-turtle, this guy is just a troll. Look at his profile page and you'll see that pretty much every "contribution" he's made is a complete and utter spit in the face to the open-source community. I'd close this issue if I were you.

You have made an AWESOME project. I am looking at getting it to work on either my Windows or Linux server. I'll let you know if I hit any bumps in the road, but @lukascomer, this is **NOT** how you make an issue on a repository.

**Comment by lukascomer** [comment]
I'll give you my number if you wanna talk sht.

**Comment by TheModdersDen** [comment]
> I'll give you my number if you wanna talk sht.

I'm not talking dirty. I'm just talking facts. Be a decent human being.

Take it or leave it.

**Comment by TheModdersDen** [comment]
Regardless of all that has been said, I **can** confirm that the latest Docker build (from the latest GitHub commit) works on Windows 11 using Docker Compose.

See the attached screenshot below for proof of working order:
![image](https://github.com/mekb-turtle/discord-ai-bot/assets/3487232/4307b706-456a-4be9-ada6-2cb2ae88f348)

**Comment by mekb-turtle** [comment]
> @mekb-turtle, this guy is just a troll. Look at his profile page and you'll see that pretty much every "contribution" he's made is a complete and utter spit in the face to the open-source community. I'd close this issue if I were you.

yeah, i'm less likely to help people who are rude to me. plus this looks like an issue with discord.js, so I'm closing this issue
